{"uuid": "e84a4e97-e12d-42bf-a98b-0f09f408bbce", "children": ["87a1c508-638c-4904-94c8-fe5a24ab8907"], "befores": [{"name": "get_reset_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input class=\"text input__textfield text_type_main-default\" name=\"name\" type=\"text\"> is not clickable at point (750,385) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 897, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/conftest.py\", line 35, in get_reset_page\n    recovery_page.set_email_to_field()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/recovery_page.py\", line 29, in set_email_to_field\n    self.click_email_field()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/recovery_page.py\", line 16, in click_email_field\n    self.driver.find_element(*RecoveryPageLocators.EMAIL_FIELD).click()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Перейти на страницу ввода нового пароля", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input class=\"text input__textfield text_type_main-default\" name=\"name\" type=\"text\"> is not clickable at point (750,385) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/conftest.py\", line 35, in get_reset_page\n    recovery_page.set_email_to_field()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/recovery_page.py\", line 29, in set_email_to_field\n    self.click_email_field()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/recovery_page.py\", line 16, in click_email_field\n    self.driver.find_element(*RecoveryPageLocators.EMAIL_FIELD).click()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Открыть страницу \"Восстановления пароля", "status": "passed", "start": 1724130588337, "stop": 1724130588506}, {"name": "Ввести почту в поле email", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input class=\"text input__textfield text_type_main-default\" name=\"name\" type=\"text\"> is not clickable at point (750,385) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/recovery_page.py\", line 29, in set_email_to_field\n    self.click_email_field()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/recovery_page.py\", line 16, in click_email_field\n    self.driver.find_element(*RecoveryPageLocators.EMAIL_FIELD).click()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1724130588506, "stop": 1724130588520}], "parameters": [{"name": "driver", "value": "<selenium.webdriver.firefox.webdriver.WebDriver (session=\"bebe2bef-df7c-4624-b41c-e838c89d2f01\")>"}], "start": 1724130588337, "stop": 1724130588521}], "start": 1724130588337, "stop": 1724130588521}], "start": 1724130588337, "stop": 1724130588538}